// const jwt_decode = require('jwt-decode');

// const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiSm9lbCIsImxhc3RuYW1lIjoiTmFhcmVuZG9ycCIsInVzZXJuYW1lIjoibjNyZGNsYXNoMTkiLCJlbWFpbCI6ImpvZWwxOUB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGw1cnlOLkM4aE93a3Nqei50TmNKdi4uNkFTdTFVUE5tUm1hUEgxRmc4NkgwSzguM3hqWTRLIiwiY3JlYXRlZF9hdCI6IjIwMjEtMDYtMTlUMTk6MDk6NTEuMDAwWiIsInVwZGF0ZWRfYXQiOm51bGwsImRlbGV0ZWRfYXQiOm51bGx9LCJpYXQiOjE2MjQ5MDcyMDksImV4cCI6MTYyNDk5MzYwOX0.tEUyB66jJDSzptvOCMN_97f_eZIyEEpObpj4DO-t0zE"


// console.log(jwt_decode(token))